//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.34209
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace SDR.Configuration.Properties {
    
    
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.VisualStudio.Editors.SettingsDesigner.SettingsSingleFileGenerator", "10.0.0.0")]
    internal sealed partial class ProjectSettings : global::System.Configuration.ApplicationSettingsBase {
        
        private static ProjectSettings defaultInstance = ((ProjectSettings)(global::System.Configuration.ApplicationSettingsBase.Synchronized(new ProjectSettings())));
        
        public static ProjectSettings Default {
            get {
                return defaultInstance;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("<?xml version=\"1.0\" encoding=\"utf-16\"?>\r\n<ArrayOfString xmlns:xsi=\"http://www.w3." +
            "org/2001/XMLSchema-instance\" xmlns:xsd=\"http://www.w3.org/2001/XMLSchema\" />")]
        public global::System.Collections.Specialized.StringCollection AddressesLayers {
            get {
                return ((global::System.Collections.Specialized.StringCollection)(this["AddressesLayers"]));
            }
            set {
                this["AddressesLayers"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("<?xml version=\"1.0\" encoding=\"utf-16\"?>\r\n<ArrayOfString xmlns:xsi=\"http://www.w3." +
            "org/2001/XMLSchema-instance\" xmlns:xsd=\"http://www.w3.org/2001/XMLSchema\" />")]
        public global::System.Collections.Specialized.StringCollection RoadsLayers {
            get {
                return ((global::System.Collections.Specialized.StringCollection)(this["RoadsLayers"]));
            }
            set {
                this["RoadsLayers"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("<?xml version=\"1.0\" encoding=\"utf-16\"?>\r\n<ArrayOfString xmlns:xsi=\"http://www.w3." +
            "org/2001/XMLSchema-instance\" xmlns:xsd=\"http://www.w3.org/2001/XMLSchema\" />")]
        public global::System.Collections.Specialized.StringCollection KeyLocationsLayers {
            get {
                return ((global::System.Collections.Specialized.StringCollection)(this["KeyLocationsLayers"]));
            }
            set {
                this["KeyLocationsLayers"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("")]
        public string NotesLayer {
            get {
                return ((string)(this["NotesLayer"]));
            }
            set {
                this["NotesLayer"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("")]
        public string CityLimitsLayer {
            get {
                return ((string)(this["CityLimitsLayer"]));
            }
            set {
                this["CityLimitsLayer"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("")]
        public string CellSectorsLayer {
            get {
                return ((string)(this["CellSectorsLayer"]));
            }
            set {
                this["CellSectorsLayer"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("")]
        public string EsnsLayer {
            get {
                return ((string)(this["EsnsLayer"]));
            }
            set {
                this["EsnsLayer"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("")]
        public string ParcelsLayer {
            get {
                return ((string)(this["ParcelsLayer"]));
            }
            set {
                this["ParcelsLayer"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("")]
        public string HydrantsLayer {
            get {
                return ((string)(this["HydrantsLayer"]));
            }
            set {
                this["HydrantsLayer"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("POINT")]
        public string AddressesProjectType {
            get {
                return ((string)(this["AddressesProjectType"]));
            }
            set {
                this["AddressesProjectType"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("POINT")]
        public string KeyLocationsProjectType {
            get {
                return ((string)(this["KeyLocationsProjectType"]));
            }
            set {
                this["KeyLocationsProjectType"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("Black")]
        public global::System.Drawing.Color MapBgColor {
            get {
                return ((global::System.Drawing.Color)(this["MapBgColor"]));
            }
            set {
                this["MapBgColor"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("kMap_MyMap")]
        public string ActiveMapViewKey {
            get {
                return ((string)(this["ActiveMapViewKey"]));
            }
            set {
                this["ActiveMapViewKey"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("My Map")]
        public string ActiveMapViewCaption {
            get {
                return ((string)(this["ActiveMapViewCaption"]));
            }
            set {
                this["ActiveMapViewCaption"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("LimeGreen")]
        public global::System.Drawing.Color GraphicPointColor {
            get {
                return ((global::System.Drawing.Color)(this["GraphicPointColor"]));
            }
            set {
                this["GraphicPointColor"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("Triangle")]
        public string GraphicPointStyle {
            get {
                return ((string)(this["GraphicPointStyle"]));
            }
            set {
                this["GraphicPointStyle"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("18")]
        public int GraphicPointSize {
            get {
                return ((int)(this["GraphicPointSize"]));
            }
            set {
                this["GraphicPointSize"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("Orange")]
        public global::System.Drawing.Color GraphicLineColor {
            get {
                return ((global::System.Drawing.Color)(this["GraphicLineColor"]));
            }
            set {
                this["GraphicLineColor"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("5")]
        public int GraphicLineSize {
            get {
                return ((int)(this["GraphicLineSize"]));
            }
            set {
                this["GraphicLineSize"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("Orange")]
        public global::System.Drawing.Color GraphicLineBorderColor {
            get {
                return ((global::System.Drawing.Color)(this["GraphicLineBorderColor"]));
            }
            set {
                this["GraphicLineBorderColor"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("Flat")]
        public string GraphicLineCap {
            get {
                return ((string)(this["GraphicLineCap"]));
            }
            set {
                this["GraphicLineCap"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("Solid")]
        public string GraphicLineStyle {
            get {
                return ((string)(this["GraphicLineStyle"]));
            }
            set {
                this["GraphicLineStyle"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("3")]
        public int HydrantSearchCount {
            get {
                return ((int)(this["HydrantSearchCount"]));
            }
            set {
                this["HydrantSearchCount"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("False")]
        public bool SearchUsePretypes {
            get {
                return ((bool)(this["SearchUsePretypes"]));
            }
            set {
                this["SearchUsePretypes"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("0.05")]
        public decimal SearchZoomFactor {
            get {
                return ((decimal)(this["SearchZoomFactor"]));
            }
            set {
                this["SearchZoomFactor"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("250")]
        public int SearchBufferDistance {
            get {
                return ((int)(this["SearchBufferDistance"]));
            }
            set {
                this["SearchBufferDistance"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("False")]
        public bool SearchQueryParserLogging {
            get {
                return ((bool)(this["SearchQueryParserLogging"]));
            }
            set {
                this["SearchQueryParserLogging"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("250")]
        public int HydrantSearchDistance {
            get {
                return ((int)(this["HydrantSearchDistance"]));
            }
            set {
                this["HydrantSearchDistance"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("Disabled")]
        public string AliMode {
            get {
                return ((string)(this["AliMode"]));
            }
            set {
                this["AliMode"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("")]
        public string AliSdrServerDbPath {
            get {
                return ((string)(this["AliSdrServerDbPath"]));
            }
            set {
                this["AliSdrServerDbPath"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("127.0.0.1")]
        public string AliSdrServerUdpHost {
            get {
                return ((string)(this["AliSdrServerUdpHost"]));
            }
            set {
                this["AliSdrServerUdpHost"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("777")]
        public int AliSdrServerUdpPort {
            get {
                return ((int)(this["AliSdrServerUdpPort"]));
            }
            set {
                this["AliSdrServerUdpPort"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("")]
        public string AliGlobalCadLogPath {
            get {
                return ((string)(this["AliGlobalCadLogPath"]));
            }
            set {
                this["AliGlobalCadLogPath"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("")]
        public string AliEnterpolTableName {
            get {
                return ((string)(this["AliEnterpolTableName"]));
            }
            set {
                this["AliEnterpolTableName"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("")]
        public string AliEnterpolDataSource {
            get {
                return ((string)(this["AliEnterpolDataSource"]));
            }
            set {
                this["AliEnterpolDataSource"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("SDRCADInterface")]
        public string AliEnterpolInitialCatalog {
            get {
                return ((string)(this["AliEnterpolInitialCatalog"]));
            }
            set {
                this["AliEnterpolInitialCatalog"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("")]
        public string AliGlobalCadArchivePath {
            get {
                return ((string)(this["AliGlobalCadArchivePath"]));
            }
            set {
                this["AliGlobalCadArchivePath"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("")]
        public string AliGlobalCadConfigPath {
            get {
                return ((string)(this["AliGlobalCadConfigPath"]));
            }
            set {
                this["AliGlobalCadConfigPath"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("127.0.0.1")]
        public string AliNetworkfleetUdpHost {
            get {
                return ((string)(this["AliNetworkfleetUdpHost"]));
            }
            set {
                this["AliNetworkfleetUdpHost"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("1111")]
        public int AliNetworkfleetUdpPort {
            get {
                return ((int)(this["AliNetworkfleetUdpPort"]));
            }
            set {
                this["AliNetworkfleetUdpPort"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("False")]
        public bool AliUseNetworkfleet {
            get {
                return ((bool)(this["AliUseNetworkfleet"]));
            }
            set {
                this["AliUseNetworkfleet"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("DarkTurquoise")]
        public global::System.Drawing.Color AliNetworkfleetPointColor {
            get {
                return ((global::System.Drawing.Color)(this["AliNetworkfleetPointColor"]));
            }
            set {
                this["AliNetworkfleetPointColor"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("ESRI Transportation & Civic, 24pt")]
        public global::System.Drawing.Font AliNetworkfleetPointFont {
            get {
                return ((global::System.Drawing.Font)(this["AliNetworkfleetPointFont"]));
            }
            set {
                this["AliNetworkfleetPointFont"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("n")]
        public char AliNetworkfleetPointChar {
            get {
                return ((char)(this["AliNetworkfleetPointChar"]));
            }
            set {
                this["AliNetworkfleetPointChar"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("False")]
        public bool AliUseEnterpolAVL {
            get {
                return ((bool)(this["AliUseEnterpolAVL"]));
            }
            set {
                this["AliUseEnterpolAVL"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("")]
        public string AliEnterpolAVLTableName {
            get {
                return ((string)(this["AliEnterpolAVLTableName"]));
            }
            set {
                this["AliEnterpolAVLTableName"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("SDR_SetMyLocation")]
        public string AliEnterpolAVLSetMyLocProc {
            get {
                return ((string)(this["AliEnterpolAVLSetMyLocProc"]));
            }
            set {
                this["AliEnterpolAVLSetMyLocProc"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("SDR_WhoAmI")]
        public string AliEnterpolAVLWhoAmIProc {
            get {
                return ((string)(this["AliEnterpolAVLWhoAmIProc"]));
            }
            set {
                this["AliEnterpolAVLWhoAmIProc"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("5000")]
        public int AliEnterpolAVLUpdateFreq {
            get {
                return ((int)(this["AliEnterpolAVLUpdateFreq"]));
            }
            set {
                this["AliEnterpolAVLUpdateFreq"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("2")]
        public int AliEnterpolAVLAge1Freq {
            get {
                return ((int)(this["AliEnterpolAVLAge1Freq"]));
            }
            set {
                this["AliEnterpolAVLAge1Freq"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("5")]
        public int AliEnterpolAVLAge2Freq {
            get {
                return ((int)(this["AliEnterpolAVLAge2Freq"]));
            }
            set {
                this["AliEnterpolAVLAge2Freq"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("60")]
        public int AliEnterpolAVLAge3Freq {
            get {
                return ((int)(this["AliEnterpolAVLAge3Freq"]));
            }
            set {
                this["AliEnterpolAVLAge3Freq"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("50000")]
        public int AliEnterpolAVLReadFreq {
            get {
                return ((int)(this["AliEnterpolAVLReadFreq"]));
            }
            set {
                this["AliEnterpolAVLReadFreq"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("ESRI Transportation & Civic, 24pt")]
        public global::System.Drawing.Font AliEnterpolAVLSymbolFont {
            get {
                return ((global::System.Drawing.Font)(this["AliEnterpolAVLSymbolFont"]));
            }
            set {
                this["AliEnterpolAVLSymbolFont"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("j")]
        public char AliEnterpolAVLLEChar {
            get {
                return ((char)(this["AliEnterpolAVLLEChar"]));
            }
            set {
                this["AliEnterpolAVLLEChar"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("d")]
        public char AliEnterpolAVLEMSChar {
            get {
                return ((char)(this["AliEnterpolAVLEMSChar"]));
            }
            set {
                this["AliEnterpolAVLEMSChar"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("m")]
        public char AliEnterpolAVLFDChar {
            get {
                return ((char)(this["AliEnterpolAVLFDChar"]));
            }
            set {
                this["AliEnterpolAVLFDChar"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("Cyan")]
        public global::System.Drawing.Color AliEnterpolAVLLEColor {
            get {
                return ((global::System.Drawing.Color)(this["AliEnterpolAVLLEColor"]));
            }
            set {
                this["AliEnterpolAVLLEColor"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("LimeGreen")]
        public global::System.Drawing.Color AliEnterpolAVLEMSColor {
            get {
                return ((global::System.Drawing.Color)(this["AliEnterpolAVLEMSColor"]));
            }
            set {
                this["AliEnterpolAVLEMSColor"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("Red")]
        public global::System.Drawing.Color AliEnterpolAVLFDColor {
            get {
                return ((global::System.Drawing.Color)(this["AliEnterpolAVLFDColor"]));
            }
            set {
                this["AliEnterpolAVLFDColor"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("SDRActiveUnitsView")]
        public string AliEnterpolAVLInitialCatalog {
            get {
                return ((string)(this["AliEnterpolAVLInitialCatalog"]));
            }
            set {
                this["AliEnterpolAVLInitialCatalog"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("True")]
        public bool AliEnterpolAvlAutoHideInactiveUnits {
            get {
                return ((bool)(this["AliEnterpolAvlAutoHideInactiveUnits"]));
            }
            set {
                this["AliEnterpolAvlAutoHideInactiveUnits"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("Fuchsia")]
        public global::System.Drawing.Color AliEnterpolAVLMyVehicleColor {
            get {
                return ((global::System.Drawing.Color)(this["AliEnterpolAVLMyVehicleColor"]));
            }
            set {
                this["AliEnterpolAVLMyVehicleColor"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("Gray")]
        public global::System.Drawing.Color AliEnterpolAVLInactiveColor {
            get {
                return ((global::System.Drawing.Color)(this["AliEnterpolAVLInactiveColor"]));
            }
            set {
                this["AliEnterpolAVLInactiveColor"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("Microsoft Sans Serif, 15.75pt")]
        public global::System.Drawing.Font AliEnterpolAVLLabelFont {
            get {
                return ((global::System.Drawing.Font)(this["AliEnterpolAVLLabelFont"]));
            }
            set {
                this["AliEnterpolAVLLabelFont"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("Above")]
        public string AliEnterpolAVLLabelAlignment {
            get {
                return ((string)(this["AliEnterpolAVLLabelAlignment"]));
            }
            set {
                this["AliEnterpolAVLLabelAlignment"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("0")]
        public int AliEnterpolAVLLabelXOffset {
            get {
                return ((int)(this["AliEnterpolAVLLabelXOffset"]));
            }
            set {
                this["AliEnterpolAVLLabelXOffset"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("-5")]
        public int AliEnterpolAVLLabelYOffset {
            get {
                return ((int)(this["AliEnterpolAVLLabelYOffset"]));
            }
            set {
                this["AliEnterpolAVLLabelYOffset"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("Microsoft Sans Serif, 15.75pt")]
        public global::System.Drawing.Font AliNetworkfleetLabelFont {
            get {
                return ((global::System.Drawing.Font)(this["AliNetworkfleetLabelFont"]));
            }
            set {
                this["AliNetworkfleetLabelFont"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("Above")]
        public string AliNetworkfleetLabelAlignment {
            get {
                return ((string)(this["AliNetworkfleetLabelAlignment"]));
            }
            set {
                this["AliNetworkfleetLabelAlignment"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("0")]
        public int AliNetworkfleetLabelXOffset {
            get {
                return ((int)(this["AliNetworkfleetLabelXOffset"]));
            }
            set {
                this["AliNetworkfleetLabelXOffset"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("-5")]
        public int AliNetworkfleetLabelYOffset {
            get {
                return ((int)(this["AliNetworkfleetLabelYOffset"]));
            }
            set {
                this["AliNetworkfleetLabelYOffset"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("<?xml version=\"1.0\" encoding=\"utf-16\"?>\r\n<ArrayOfString xmlns:xsi=\"http://www.w3." +
            "org/2001/XMLSchema-instance\" xmlns:xsd=\"http://www.w3.org/2001/XMLSchema\" />")]
        public global::System.Collections.Specialized.StringCollection AliNetworkfleetLabelLookup {
            get {
                return ((global::System.Collections.Specialized.StringCollection)(this["AliNetworkfleetLabelLookup"]));
            }
            set {
                this["AliNetworkfleetLabelLookup"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("2")]
        public int AliNetworkfleetAVLAge1Freq {
            get {
                return ((int)(this["AliNetworkfleetAVLAge1Freq"]));
            }
            set {
                this["AliNetworkfleetAVLAge1Freq"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("5")]
        public int AliNetworkfleetAVLAge2Freq {
            get {
                return ((int)(this["AliNetworkfleetAVLAge2Freq"]));
            }
            set {
                this["AliNetworkfleetAVLAge2Freq"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("60")]
        public int AliNetworkfleetAVLAge3Freq {
            get {
                return ((int)(this["AliNetworkfleetAVLAge3Freq"]));
            }
            set {
                this["AliNetworkfleetAVLAge3Freq"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("Fuchsia")]
        public global::System.Drawing.Color AliNetworkfleetAVLMyVehicleColor {
            get {
                return ((global::System.Drawing.Color)(this["AliNetworkfleetAVLMyVehicleColor"]));
            }
            set {
                this["AliNetworkfleetAVLMyVehicleColor"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("True")]
        public bool AliNetworkfleetAvlAutoHideInactiveUnits {
            get {
                return ((bool)(this["AliNetworkfleetAvlAutoHideInactiveUnits"]));
            }
            set {
                this["AliNetworkfleetAvlAutoHideInactiveUnits"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("Gray")]
        public global::System.Drawing.Color AliNetworkfleetAVLInactiveColor {
            get {
                return ((global::System.Drawing.Color)(this["AliNetworkfleetAVLInactiveColor"]));
            }
            set {
                this["AliNetworkfleetAVLInactiveColor"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("<?xml version=\"1.0\" encoding=\"utf-16\"?>\r\n<ArrayOfString xmlns:xsi=\"http://www.w3." +
            "org/2001/XMLSchema-instance\" xmlns:xsd=\"http://www.w3.org/2001/XMLSchema\" />")]
        public global::System.Collections.Specialized.StringCollection MapTipsLookup {
            get {
                return ((global::System.Collections.Specialized.StringCollection)(this["MapTipsLookup"]));
            }
            set {
                this["MapTipsLookup"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("<?xml version=\"1.0\" encoding=\"utf-16\"?>\r\n<ArrayOfString xmlns:xsi=\"http://www.w3." +
            "org/2001/XMLSchema-instance\" xmlns:xsd=\"http://www.w3.org/2001/XMLSchema\" />")]
        public global::System.Collections.Specialized.StringCollection NotesFields {
            get {
                return ((global::System.Collections.Specialized.StringCollection)(this["NotesFields"]));
            }
            set {
                this["NotesFields"] = value;
            }
        }
    }
}
