//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.34209
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DotSpatial.SDR.Plugins.ALI.Properties {
    
    
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.VisualStudio.Editors.SettingsDesigner.SettingsSingleFileGenerator", "10.0.0.0")]
    internal sealed partial class EnterpolAvlConfig : global::System.Configuration.ApplicationSettingsBase {
        
        private static EnterpolAvlConfig defaultInstance = ((EnterpolAvlConfig)(global::System.Configuration.ApplicationSettingsBase.Synchronized(new EnterpolAvlConfig())));
        
        public static EnterpolAvlConfig Default {
            get {
                return defaultInstance;
            }
        }
        
        [global::System.Configuration.ApplicationScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("UnitName, UnitVehicleNumber")]
        public string UnitDisplayQuery {
            get {
                return ((string)(this["UnitDisplayQuery"]));
            }
        }
    }
}
