//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.34209
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DotSpatial.SDR.Plugins.ALI.Properties {
    
    
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.VisualStudio.Editors.SettingsDesigner.SettingsSingleFileGenerator", "10.0.0.0")]
    internal sealed partial class GlobalCadConfig : global::System.Configuration.ApplicationSettingsBase {
        
        private static GlobalCadConfig defaultInstance = ((GlobalCadConfig)(global::System.Configuration.ApplicationSettingsBase.Synchronized(new GlobalCadConfig())));
        
        public static GlobalCadConfig Default {
            get {
                return defaultInstance;
            }
        }
        
        [global::System.Configuration.ApplicationScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("Parser Config")]
        public string IniKeyLookup {
            get {
                return ((string)(this["IniKeyLookup"]));
            }
        }
    }
}
